FROM alpine:3.11
RUN apk update && \
    apk add --no-cache ca-certificates && \
    apk add --no-cache curl bash tree tzdata nginx && \
    cp -rf /usr/share/zoneinfo/Asia/Taipei /etc/localtime
 
# 設置變量
ENV NGINX_VERSION 1.14.0
RUN ln -sf /usr/share/zoneinfo/Asia/Taipei /etc/localtime
RUN echo 'Asia/Taipei' >/etc/timezone

WORKDIR /usr/share/nginx/html

COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/default.conf /etc/nginx/conf.d/default.conf
COPY docker/entrypoint.sh .
COPY ../app/dist/ ./ 
COPY ../app/dist/index.html ./

ENTRYPOINT ["./entrypoint.sh"]
