version: '2.1'
services:
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - '80:80'
        mem_limit: 2048m
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./log:/var/log/nginx;
        restart: always
        extra_hosts:
            - "localhost:${SELF_IP}"
        networks: 
            - nginx-net
networks:
    nginx-net:
        external: true
        name: nginx-net
